import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  ActivityIndicator,
  StyleSheet,
  Platform,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { getSharedReport, SharedReport } from '../../services/shareService';
import { Ionicons } from '@expo/vector-icons';

export default function SharedReportScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [loading, setLoading] = useState(true);
  const [report, setReport] = useState<SharedReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadReport();
  }, [id]);

  const loadReport = async () => {
    try {
      setLoading(true);
      setError(null);

      if (!id) {
        setError('Invalid report ID');
        return;
      }

      console.log('📥 Loading shared report:', id);
      const reportData = await getSharedReport(id);

      if (!reportData) {
        setError('Report not found or has expired');
        return;
      }

      setReport(reportData);
      console.log('✅ Report loaded successfully');
    } catch (err: any) {
      console.error('❌ Error loading report:', err);
      setError(err.message || 'Failed to load report');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color="#4F46E5" />
        <Text style={styles.loadingText}>Loading report...</Text>
      </View>
    );
  }

  if (error || !report) {
    return (
      <View style={styles.centerContainer}>
        <Ionicons name="alert-circle-outline" size={64} color="#EF4444" />
        <Text style={styles.errorTitle}>Report Not Available</Text>
        <Text style={styles.errorMessage}>
          {error || 'This report may have expired or been removed.'}
        </Text>
      </View>
    );
  }

  // For web, render the HTML content directly
  if (Platform.OS === 'web' && report.htmlContent) {
    return (
      <ScrollView style={styles.container}>
        <div dangerouslySetInnerHTML={{ __html: report.htmlContent }} />
      </ScrollView>
    );
  }

  // For mobile, show a formatted view
  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerIcon}>
          <Ionicons name="heart" size={32} color="#4F46E5" />
        </View>
        <Text style={styles.headerTitle}>Vitals Health Report</Text>
        <Text style={styles.headerSubtitle}>Personal Health Summary</Text>
      </View>

      <View style={styles.content}>
        {/* Patient Info */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Patient Information</Text>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Name:</Text>
            <Text style={styles.infoValue}>{report.userName}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Report Date:</Text>
            <Text style={styles.infoValue}>
              {report.createdAt.toDate().toLocaleDateString()}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Period:</Text>
            <Text style={styles.infoValue}>Last {report.dateRange} days</Text>
          </View>
        </View>

        {/* Vitals Preview */}
        {report.vitals && report.vitals.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Recent Vitals</Text>
            {report.vitals.map((vital: any, index: number) => (
              <View key={index} style={styles.vitalRow}>
                <Text style={styles.vitalDate}>
                  {vital.timestamp?.toDate?.()?.toLocaleDateString() || 'N/A'}
                </Text>
                <View style={styles.vitalValues}>
                  <Text style={styles.vitalText}>
                    BP: {vital.bloodPressure.systolic}/{vital.bloodPressure.diastolic}
                  </Text>
                  <Text style={styles.vitalText}>HR: {vital.heartRate}</Text>
                  <Text style={styles.vitalText}>SpO₂: {vital.spO2}%</Text>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Ionicons name="information-circle" size={20} color="#F59E0B" />
          <Text style={styles.disclaimerText}>
            This report is for informational purposes only and should not replace professional
            medical advice.
          </Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by HealthMate App</Text>
          <Text style={styles.footerText}>
            Expires: {report.expiresAt.toDate().toLocaleDateString()}
          </Text>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#F9FAFB',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#6B7280',
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginTop: 16,
    marginBottom: 8,
  },
  errorMessage: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  header: {
    backgroundColor: '#FFFFFF',
    padding: 30,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
  },
  content: {
    padding: 20,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  infoLabel: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '600',
  },
  vitalRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  vitalDate: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 6,
  },
  vitalValues: {
    flexDirection: 'row',
    gap: 16,
  },
  vitalText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '500',
  },
  disclaimer: {
    flexDirection: 'row',
    backgroundColor: '#FFFBEB',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginBottom: 16,
    gap: 12,
  },
  disclaimerText: {
    flex: 1,
    fontSize: 12,
    color: '#78350F',
    lineHeight: 18,
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  footerText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 4,
  },
});
