import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Platform,
  StyleSheet,
  Modal,
  Share,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { readVitalsForDays } from '../../../services/vitalsService';
import { generateAndSharePDF, generateReportPreview } from '../../../services/pdfService';
import { createShareableReport, generateShareableURL } from '../../../services/shareService';
import { logActivity } from '../../../services/activityService';

export default function ExportScreen() {
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [dateRange, setDateRange] = useState(30);
  const [preview, setPreview] = useState<any>(null);
  const [showShareModal, setShowShareModal] = useState(false);
  const [shareLink, setShareLink] = useState('');

  useEffect(() => {
    loadPreview();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dateRange]);

  const loadPreview = async () => {
    try {
      setLoading(true);
      console.log('🔄 Loading preview for', dateRange, 'days');
      
      const vitals = await readVitalsForDays(dateRange);
      console.log('📊 Vitals loaded:', vitals.length, 'records');
      
      if (vitals.length > 0) {
        console.log('📋 Sample vital:', vitals[0]);
      }
      
      const previewData = generateReportPreview(vitals, dateRange);
      console.log('✅ Preview generated:', {
        totalRecords: previewData.totalRecords,
        averages: previewData.averages,
        userName: previewData.userName,
      });
      
      setPreview(previewData);
    } catch (error: any) {
      console.error('❌ Error loading preview:', error);
      console.error('Error details:', error.message);
      Alert.alert('Error', `Failed to load report preview: ${error.message || 'Unknown error'}`);
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async () => {
    console.log('🔵 Export button clicked');
    console.log('📊 Preview data:', preview);
    console.log('📅 Date range:', dateRange);
    
    try {
      setExporting(true);
      console.log('📥 Fetching vitals...');
      const vitals = await readVitalsForDays(dateRange);
      console.log('✅ Vitals fetched:', vitals.length, 'records');
      
      if (vitals.length === 0) {
        console.log('⚠️ No vitals data found');
        Alert.alert('No Data', 'No vitals data available for the selected period');
        setExporting(false);
        return;
      }

      console.log('📄 Generating PDF...');
      await generateAndSharePDF(vitals, dateRange);
      console.log('✅ PDF generated successfully');
      
      // Log activity
      await logActivity('report_exported', `Health report for last ${dateRange} days`);
      
      Alert.alert(
        'Success',
        Platform.OS === 'web' 
          ? 'Report downloaded successfully!' 
          : 'Report generated and ready to share!'
      );
    } catch (error: any) {
      console.error('❌ Error exporting PDF:', error);
      console.error('Error details:', error.message, error.stack);
      Alert.alert('Error', `Failed to generate PDF report: ${error.message || 'Unknown error'}`);
    } finally {
      setExporting(false);
      console.log('🔵 Export process completed');
    }
  };

  const handleShare = async () => {
    console.log('📤 Share button clicked');
    
    try {
      setExporting(true);
      const vitals = await readVitalsForDays(dateRange);
      
      if (vitals.length === 0) {
        Alert.alert('No Data', 'No vitals data available for the selected period');
        setExporting(false);
        return;
      }

      // Create shareable report in Firestore
      console.log('📝 Creating shareable report in database...');
      const reportId = await createShareableReport(vitals, dateRange);
      const shareableUrl = generateShareableURL(reportId);
      console.log('✅ Shareable URL created:', shareableUrl);

      if (Platform.OS === 'web') {
        // For web: Show modal with shareable link
        setShareLink(shareableUrl);
        setShowShareModal(true);
        console.log('🌐 Web share modal opened');
      } else {
        // For mobile: Use native share dialog
        try {
          const result = await Share.share({
            message: `Check out my Health Report from HealthMate!\n\nReport Period: Last ${dateRange} days\nTotal Records: ${vitals.length}\n\nView Report: ${shareableUrl}\n\nGenerated by HealthMate App`,
            title: 'Health Report',
            url: shareableUrl,
          });

          if (result.action === Share.sharedAction) {
            console.log('✅ Report shared successfully');
            Alert.alert('Success', 'Report shared successfully!');
          }
        } catch (error: any) {
          console.error('❌ Error sharing:', error);
          Alert.alert('Error', `Failed to share report: ${error.message}`);
        }
      }
    } catch (error: any) {
      console.error('❌ Error preparing share:', error);
      Alert.alert('Error', `Failed to prepare report: ${error.message || 'Unknown error'}`);
    } finally {
      setExporting(false);
    }
  };

  const copyLinkToClipboard = async () => {
    try {
      if (Platform.OS === 'web' && typeof navigator !== 'undefined' && navigator.clipboard) {
        await navigator.clipboard.writeText(shareLink);
      } else {
        await Clipboard.setStringAsync(shareLink);
      }
      Alert.alert('Success', 'Link copied to clipboard!');
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      Alert.alert('Error', 'Failed to copy link');
    }
  };

  const closeShareModal = () => {
    setShowShareModal(false);
    setShareLink('');
  };

  const dateRangeOptions = [
    { label: 'Last 7 Days', value: 7 },
    { label: 'Last 30 Days', value: 30 },
    { label: 'Last 90 Days', value: 90 },
    { label: 'Last 6 Months', value: 180 },
    { label: 'Last Year', value: 365 },
  ];

  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Report Preview</Text>
        <Text style={styles.headerSubtitle}>Review your vitals report before sharing</Text>
      </View>

      <View style={styles.content}>
        {/* Action Buttons */}
        <View style={styles.actionButtons}>
          <TouchableOpacity
            onPress={handleExport}
            disabled={exporting || loading || !preview || preview.totalRecords === 0}
            style={[
              styles.downloadButton,
              (exporting || loading || !preview || preview.totalRecords === 0) && styles.buttonDisabled
            ]}
          >
            {exporting ? (
              <ActivityIndicator size="small" color="#FFFFFF" />
            ) : (
              <Ionicons name="download-outline" size={20} color="#FFFFFF" />
            )}
            <Text style={styles.downloadButtonText}>
              {exporting ? 'Generating...' : 'Download PDF'}
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={handleShare}
            disabled={exporting || loading || !preview || preview.totalRecords === 0}
            style={[
              styles.shareButton,
              (exporting || loading || !preview || preview.totalRecords === 0) && styles.buttonDisabled
            ]}
          >
            <Ionicons name="share-social-outline" size={20} color="#FFFFFF" />
            <Text style={styles.shareButtonText}>Share Report</Text>
          </TouchableOpacity>
        </View>

        {/* Loading State */}
        {loading ? (
          <View style={styles.loadingCard}>
            <ActivityIndicator size="large" color="#4F46E5" />
            <Text style={styles.loadingText}>Loading preview...</Text>
          </View>
        ) : preview ? (
          <>
            {/* Main Report Card */}
            <View style={styles.reportCard}>
              {/* Header with Heart Icon */}
              <View style={styles.reportHeader}>
                <View style={styles.reportTitleContainer}>
                  <Text style={styles.reportTitle}>Vitals Health Report</Text>
                  <Text style={styles.reportSubtitle}>Personal Health Summary</Text>
                </View>
                <View style={styles.heartIcon}>
                  <Ionicons name="heart" size={28} color="#4F46E5" />
                </View>
              </View>

              {/* Patient Info */}
              <View style={styles.patientInfo}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Patient Name</Text>
                  <Text style={styles.infoLabel}>Report Date</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoValue}>{preview.userName}</Text>
                  <Text style={styles.infoValue}>{preview.reportDate}</Text>
                </View>
              </View>

              {/* Report Period */}
              <View style={styles.reportPeriod}>
                <Text style={styles.reportPeriodText}>Report Period: Last {dateRange} Days</Text>
                <Text style={styles.reportPeriodDate}>{preview.dateRange}</Text>
              </View>

              {/* Vital Signs Summary */}
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Vital Signs Summary</Text>
                
                <View style={styles.vitalsGrid}>
                  {/* Blood Pressure */}
                  <View style={styles.vitalCard}>
                    <View style={styles.vitalHeader}>
                      <Ionicons name="heart-outline" size={20} color="#EF4444" />
                      <Text style={styles.vitalLabel}>Blood Pressure</Text>
                    </View>
                    <Text style={styles.vitalValue}>
                      {preview.averages?.bloodPressure.systolic || '--'}/
                      {preview.averages?.bloodPressure.diastolic || '--'}
                    </Text>
                    <Text style={styles.vitalUnit}>mmHg</Text>
                    <Text style={styles.vitalRange}>Range: Normal</Text>
                  </View>

                  {/* Heart Rate */}
                  <View style={styles.vitalCard}>
                    <View style={styles.vitalHeader}>
                      <Ionicons name="pulse-outline" size={20} color="#F59E0B" />
                      <Text style={styles.vitalLabel}>Heart Rate</Text>
                    </View>
                    <Text style={styles.vitalValue}>
                      {preview.averages?.heartRate || '--'}
                    </Text>
                    <Text style={styles.vitalUnit}>BPM</Text>
                    <Text style={styles.vitalRange}>Range: Normal</Text>
                  </View>

                  {/* Blood Oxygen */}
                  <View style={styles.vitalCard}>
                    <View style={styles.vitalHeader}>
                      <Ionicons name="water-outline" size={20} color="#3B82F6" />
                      <Text style={styles.vitalLabel}>Blood Oxygen</Text>
                    </View>
                    <Text style={styles.vitalValue}>
                      {preview.averages?.spO2 || '--'}%
                    </Text>
                    <Text style={styles.vitalUnit}>SpO₂</Text>
                    <Text style={styles.vitalRange}>Range: Normal</Text>
                  </View>

                  {/* Temperature */}
                  <View style={styles.vitalCard}>
                    <View style={styles.vitalHeader}>
                      <Ionicons name="thermometer-outline" size={20} color="#8B5CF6" />
                      <Text style={styles.vitalLabel}>Temperature</Text>
                    </View>
                    <Text style={styles.vitalValue}>
                      {preview.averages?.temperature || '--'}°F
                    </Text>
                    <Text style={styles.vitalUnit}>Fahrenheit</Text>
                    <Text style={styles.vitalRange}>Range: Normal</Text>
                  </View>
                </View>
              </View>

              {/* Key Insights */}
              {preview.insights && preview.insights.length > 0 && (
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Key Insights</Text>
                  {preview.insights.slice(0, 3).map((insight: any, index: number) => (
                    <View key={index} style={styles.insightItem}>
                      <View style={styles.insightBullet} />
                      <View style={styles.insightContent}>
                        <Text style={styles.insightTitle}>{insight.title}</Text>
                        <Text style={styles.insightMessage}>{insight.message}</Text>
                      </View>
                    </View>
                  ))}
                </View>
              )}

              {/* Medical Disclaimer */}
              <View style={styles.disclaimer}>
                <Text style={styles.disclaimerTitle}>Medical Disclaimer</Text>
                <Text style={styles.disclaimerText}>
                  This report is for informational purposes only and should not replace professional 
                  medical advice. Always consult with your healthcare provider for medical decisions.
                </Text>
                <Text style={styles.disclaimerFooter}>
                  Generated by HealthTracker App on {preview.reportDate}
                </Text>
              </View>
            </View>
          </>
        ) : (
          <View style={styles.noDataCard}>
            <Ionicons name="document-text-outline" size={64} color="#D1D5DB" />
            <Text style={styles.noDataText}>No data available</Text>
            <Text style={styles.noDataSubtext}>Add some vitals to generate a report</Text>
          </View>
        )}
      </View>

      {/* Share Modal for Web */}
      <Modal
        visible={showShareModal}
        transparent={true}
        animationType="fade"
        onRequestClose={closeShareModal}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Share Report</Text>
              <TouchableOpacity onPress={closeShareModal}>
                <Ionicons name="close" size={24} color="#6B7280" />
              </TouchableOpacity>
            </View>

            <View style={styles.modalBody}>
              <View style={styles.linkContainer}>
                <Ionicons name="link" size={24} color="#4F46E5" />
                <Text style={styles.linkLabel}>Shareable Link</Text>
              </View>

              <View style={styles.linkBox}>
                <Text style={styles.linkText} numberOfLines={1}>
                  {shareLink}
                </Text>
              </View>

              <TouchableOpacity
                style={styles.copyButton}
                onPress={copyLinkToClipboard}
              >
                <Ionicons name="copy-outline" size={20} color="#FFFFFF" />
                <Text style={styles.copyButtonText}>Copy Link</Text>
              </TouchableOpacity>

              <Text style={styles.modalNote}>
                Share this link with anyone to give them access to your health report.
              </Text>
            </View>
          </View>
        </View>
      </Modal>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
  },
  content: {
    padding: 20,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  downloadButton: {
    flex: 1,
    backgroundColor: '#4F46E5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  shareButton: {
    flex: 1,
    backgroundColor: '#10B981',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  buttonDisabled: {
    backgroundColor: '#D1D5DB',
  },
  downloadButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  shareButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  loadingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 60,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
    color: '#6B7280',
  },
  reportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  reportTitleContainer: {
    flex: 1,
  },
  reportTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  reportSubtitle: {
    fontSize: 13,
    color: '#6B7280',
  },
  heartIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  patientInfo: {
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  infoLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  reportPeriod: {
    backgroundColor: '#EEF2FF',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    alignItems: 'center',
  },
  reportPeriodText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4F46E5',
    marginBottom: 2,
  },
  reportPeriodDate: {
    fontSize: 11,
    color: '#6366F1',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 16,
  },
  vitalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  vitalCard: {
    width: '48%',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  vitalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 6,
  },
  vitalLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  vitalValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 2,
  },
  vitalUnit: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  vitalRange: {
    fontSize: 11,
    color: '#10B981',
    fontWeight: '600',
  },
  insightItem: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  insightBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
    marginTop: 6,
    marginRight: 10,
  },
  insightContent: {
    flex: 1,
  },
  insightTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  insightMessage: {
    fontSize: 12,
    color: '#6B7280',
    lineHeight: 18,
  },
  disclaimer: {
    backgroundColor: '#FFFBEB',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginTop: 8,
  },
  disclaimerTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: 6,
  },
  disclaimerText: {
    fontSize: 11,
    color: '#78350F',
    lineHeight: 16,
    marginBottom: 8,
  },
  disclaimerFooter: {
    fontSize: 10,
    color: '#92400E',
    fontStyle: 'italic',
  },
  noDataCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 60,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  noDataText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 16,
  },
  noDataSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '100%',
    maxWidth: 500,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  modalBody: {
    padding: 20,
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  linkLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  linkBox: {
    backgroundColor: '#F3F4F6',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 16,
  },
  linkText: {
    fontSize: 14,
    color: '#4F46E5',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  copyButton: {
    backgroundColor: '#4F46E5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
    marginBottom: 16,
  },
  copyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  modalNote: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
  },
});
